import { TemplateVariant } from './templates-hero';
const id = () => Math.random().toString(36).substr(2, 9);

export const benefitsTemplates: TemplateVariant[] = [
  {
    name: '아이콘 + 제목 (세로)',
    preview: '🛡️',
    bg: { type: 'color', value: '#ffffff' },
    elements: [
      { id: id(), type: 'text', content: '왜 우리 제품인가요?', styles: { fontSize: '22px', fontWeight: 'bold', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'icon', content: 'ShieldCheck', styles: { fontSize: '36px', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '안전한 소재', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center', margin: '8px 0 4px' } },
      { id: id(), type: 'text', content: '피부 자극 테스트 완료', styles: { fontSize: '13px', color: '#888', textAlign: 'center' } },
      { id: id(), type: 'icon', content: 'Truck', styles: { fontSize: '36px', color: '#2563eb', textAlign: 'center', margin: '24px 0 0' } },
      { id: id(), type: 'text', content: '무료 배송', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center', margin: '8px 0 4px' } },
      { id: id(), type: 'text', content: '전 제품 무료 배송', styles: { fontSize: '13px', color: '#888', textAlign: 'center' } },
      { id: id(), type: 'icon', content: 'RotateCcw', styles: { fontSize: '36px', color: '#2563eb', textAlign: 'center', margin: '24px 0 0' } },
      { id: id(), type: 'text', content: '30일 무료 반품', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center', margin: '8px 0 4px' } },
      { id: id(), type: 'text', content: '마음에 안 들면 무조건 환불', styles: { fontSize: '13px', color: '#888', textAlign: 'center' } },
    ],
  },
  {
    name: '넘버링 스타일',
    preview: '🔢',
    bg: { type: 'color', value: '#f9fafb' },
    elements: [
      { id: id(), type: 'text', content: '3가지 핵심 포인트', styles: { fontSize: '22px', fontWeight: 'bold', textAlign: 'center', margin: '0 0 24px' } },
      { id: id(), type: 'text', content: '01', styles: { fontSize: '32px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '압도적인 내구성', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center' } },
      { id: id(), type: 'text', content: '10,000회 반복 테스트 통과', styles: { fontSize: '13px', color: '#888', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'text', content: '02', styles: { fontSize: '32px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '초경량 설계', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center' } },
      { id: id(), type: 'text', content: '기존 대비 40% 가벼운 무게', styles: { fontSize: '13px', color: '#888', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'text', content: '03', styles: { fontSize: '32px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '완벽한 그립감', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center' } },
      { id: id(), type: 'text', content: '인체공학적 디자인 적용', styles: { fontSize: '13px', color: '#888', textAlign: 'center' } },
    ],
  },
  {
    name: '카드형 (배경색)',
    preview: '🃏',
    bg: { type: 'color', value: '#ffffff' },
    elements: [
      { id: id(), type: 'text', content: '왜 고객들이 선택할까요?', styles: { fontSize: '20px', fontWeight: 'bold', textAlign: 'center', margin: '0 0 16px' } },
      { id: id(), type: 'text', content: '🏆 품질 보증', styles: { fontSize: '15px', fontWeight: 'bold', backgroundColor: '#eff6ff', padding: '16px', borderRadius: '12px', textAlign: 'center' } },
      { id: id(), type: 'text', content: '🚀 당일 출고', styles: { fontSize: '15px', fontWeight: 'bold', backgroundColor: '#f0fdf4', padding: '16px', borderRadius: '12px', textAlign: 'center', margin: '8px 0' } },
      { id: id(), type: 'text', content: '💎 프리미엄 소재', styles: { fontSize: '15px', fontWeight: 'bold', backgroundColor: '#fdf4ff', padding: '16px', borderRadius: '12px', textAlign: 'center' } },
    ],
  },
  {
    name: '다크 모드 아이콘',
    preview: '🌑',
    bg: { type: 'color', value: '#111827' },
    elements: [
      { id: id(), type: 'text', content: 'WHY US', styles: { fontSize: '11px', letterSpacing: '3px', color: '#6366f1', textAlign: 'center' } },
      { id: id(), type: 'text', content: '선택의 이유', styles: { fontSize: '24px', fontWeight: 'bold', color: '#fff', textAlign: 'center', margin: '8px 0 24px' } },
      { id: id(), type: 'icon', content: 'Zap', styles: { fontSize: '32px', color: '#fbbf24', textAlign: 'center' } },
      { id: id(), type: 'text', content: '즉각적인 효과', styles: { fontSize: '15px', fontWeight: 'bold', color: '#fff', textAlign: 'center', margin: '8px 0 4px' } },
      { id: id(), type: 'text', content: '사용 즉시 체감 가능', styles: { fontSize: '12px', color: '#9ca3af', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'icon', content: 'Award', styles: { fontSize: '32px', color: '#fbbf24', textAlign: 'center' } },
      { id: id(), type: 'text', content: '수상 이력', styles: { fontSize: '15px', fontWeight: 'bold', color: '#fff', textAlign: 'center', margin: '8px 0 4px' } },
      { id: id(), type: 'text', content: '2024 올해의 제품 수상', styles: { fontSize: '12px', color: '#9ca3af', textAlign: 'center' } },
    ],
  },
  {
    name: '이미지 + 텍스트 교차',
    preview: '🖼️',
    bg: { type: 'color', value: '#fff' },
    elements: [
      { id: id(), type: 'image', content: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80', styles: { borderRadius: '12px' } },
      { id: id(), type: 'text', content: '자연에서 온 원료', styles: { fontSize: '18px', fontWeight: 'bold', textAlign: 'center', margin: '12px 0 4px' } },
      { id: id(), type: 'text', content: '100% 유기농 인증 원료만 사용합니다.', styles: { fontSize: '13px', color: '#666', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'image', content: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', styles: { borderRadius: '12px' } },
      { id: id(), type: 'text', content: '정밀한 제조 공정', styles: { fontSize: '18px', fontWeight: 'bold', textAlign: 'center', margin: '12px 0 4px' } },
      { id: id(), type: 'text', content: 'ISO 인증 시설에서 생산됩니다.', styles: { fontSize: '13px', color: '#666', textAlign: 'center' } },
    ],
  },
  {
    name: '체크리스트형',
    preview: '✅',
    bg: { type: 'color', value: '#f0fdf4' },
    elements: [
      { id: id(), type: 'text', content: '이런 분께 추천합니다', styles: { fontSize: '20px', fontWeight: 'bold', textAlign: 'center', margin: '0 0 16px' } },
      { id: id(), type: 'text', content: '✅ 피부가 예민하신 분', styles: { fontSize: '14px', padding: '10px 16px', backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #dcfce7' } },
      { id: id(), type: 'text', content: '✅ 천연 성분을 선호하시는 분', styles: { fontSize: '14px', padding: '10px 16px', backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #dcfce7', margin: '6px 0' } },
      { id: id(), type: 'text', content: '✅ 간편한 관리를 원하시는 분', styles: { fontSize: '14px', padding: '10px 16px', backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #dcfce7' } },
      { id: id(), type: 'text', content: '✅ 가성비를 중시하시는 분', styles: { fontSize: '14px', padding: '10px 16px', backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #dcfce7', margin: '6px 0' } },
    ],
  },
  {
    name: '수치 강조형',
    preview: '📊',
    bg: { type: 'color', value: '#fff' },
    elements: [
      { id: id(), type: 'text', content: '숫자로 보는 품질', styles: { fontSize: '20px', fontWeight: 'bold', textAlign: 'center', margin: '0 0 20px' } },
      { id: id(), type: 'text', content: '99.8%', styles: { fontSize: '40px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '고객 만족도', styles: { fontSize: '13px', color: '#888', textAlign: 'center', margin: '0 0 16px' } },
      { id: id(), type: 'text', content: '50만+', styles: { fontSize: '40px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '누적 판매량', styles: { fontSize: '13px', color: '#888', textAlign: 'center', margin: '0 0 16px' } },
      { id: id(), type: 'text', content: '4.9 / 5.0', styles: { fontSize: '40px', fontWeight: '900', color: '#2563eb', textAlign: 'center' } },
      { id: id(), type: 'text', content: '평균 리뷰 점수', styles: { fontSize: '13px', color: '#888', textAlign: 'center' } },
    ],
  },
  {
    name: '뱃지형 간결',
    preview: '🏅',
    bg: { type: 'color', value: '#1e1b4b' },
    elements: [
      { id: id(), type: 'text', content: '핵심 혜택', styles: { fontSize: '20px', fontWeight: 'bold', color: '#fff', textAlign: 'center', margin: '0 0 16px' } },
      { id: id(), type: 'text', content: '🛡️ 2년 무상 보증', styles: { fontSize: '14px', color: '#e0e7ff', backgroundColor: '#312e81', padding: '12px', borderRadius: '8px', textAlign: 'center' } },
      { id: id(), type: 'text', content: '🚚 무료 배송', styles: { fontSize: '14px', color: '#e0e7ff', backgroundColor: '#312e81', padding: '12px', borderRadius: '8px', textAlign: 'center', margin: '8px 0' } },
      { id: id(), type: 'text', content: '🔄 30일 환불 보장', styles: { fontSize: '14px', color: '#e0e7ff', backgroundColor: '#312e81', padding: '12px', borderRadius: '8px', textAlign: 'center' } },
    ],
  },
  {
    name: '좌측 정렬 깔끔',
    preview: '📋',
    bg: { type: 'color', value: '#fff' },
    elements: [
      { id: id(), type: 'text', content: '이 제품의 장점', styles: { fontSize: '22px', fontWeight: 'bold', textAlign: 'left', margin: '0 0 20px' } },
      { id: id(), type: 'text', content: '→ 특허받은 독자 기술 적용', styles: { fontSize: '15px', textAlign: 'left', padding: '8px 0', borderBottom: '1px solid #eee' } },
      { id: id(), type: 'text', content: '→ 업계 최저가 보장', styles: { fontSize: '15px', textAlign: 'left', padding: '8px 0', borderBottom: '1px solid #eee' } },
      { id: id(), type: 'text', content: '→ 전문 상담사 1:1 케어', styles: { fontSize: '15px', textAlign: 'left', padding: '8px 0', borderBottom: '1px solid #eee' } },
      { id: id(), type: 'text', content: '→ 평생 AS 지원', styles: { fontSize: '15px', textAlign: 'left', padding: '8px 0' } },
    ],
  },
  {
    name: '감성 스토리형',
    preview: '💫',
    bg: { type: 'color', value: '#fefce8' },
    elements: [
      { id: id(), type: 'text', content: '"처음 써본 순간,\n달라졌습니다."', styles: { fontSize: '22px', fontWeight: 'bold', textAlign: 'center', color: '#713f12', lineHeight: '1.4' } },
      { id: id(), type: 'text', content: '— 실제 사용자 리뷰 중', styles: { fontSize: '12px', color: '#a16207', textAlign: 'center', margin: '8px 0 20px' } },
      { id: id(), type: 'icon', content: 'Heart', styles: { fontSize: '28px', color: '#ef4444', textAlign: 'center' } },
      { id: id(), type: 'text', content: '10만 고객이 사랑한 제품', styles: { fontSize: '16px', fontWeight: 'bold', textAlign: 'center', margin: '8px 0' } },
    ],
  },
];
